In [10]:
import numpy as np
import pandas as pd

In [21]:
A = np.arange(1, 10).reshape(3, -1)
print(A)
print((1/A).sum(1).reshape(-1,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.83333333]
 [0.61666667]
 [0.37896825]]


首先把所有元素的倒数求出来就是1/A
再看官方示例B2,2=5×(1/4+1/5+1/6)=37/12
A中每一个元素乘的数都是对应行元素倒数之和是一个定值,我们可以先把这个定值求出来
也就是1/A每一行相加->1/A.sum(1),这里的1是axis=1，按照列顺序对行求和
之后重整形状变成一列.shape(-1,1)
再让A*这一列就是同一行的每个元素*倒数之和相加定值

In [18]:
B = A * ((1/A).sum(1).reshape(-1,1))
print(B)

[[1.83333333 3.66666667 5.5       ]
 [2.46666667 3.08333333 3.7       ]
 [2.65277778 3.03174603 3.41071429]]
