In [1]:
import numpy as np

lc easy题吧 就是练习api 习惯了cpp直接双指针+滑动窗口就能做,结合打印结果看很清楚

In [6]:
x = [1,2,5,6,7]#1,2之间为第一个空位,2,5之间为第二个空位,以此类推
print(np.diff(x)!=1)#如果一个数列是连续的,那么diff之后n个元素会形成n-1个1,如果不连续,那么不为0的所指向的空位之前全部连续,之后也全部连续,我们要做的就是比较这两个子序列谁长
print(np.r_[1,np.diff(x)!=1,1])#将前一个子序列填1,后一个也填1这样计算长度就可以直接减了,不一定非要填1 不为零的数都可以
print(np.nonzero(np.r_[1,np.diff(x)!=1,1]))#结果就是第一个子序列开始到空位的两个索引下标,和从索引下标到后一个子序列的末尾下标
print(np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])))#直接相减得到长度 如果不补1还要考虑下标和长度的事 明白第3行为什么填1了吧

[False  True False False]
[1 0 1 0 0 1]
(array([0, 2, 5], dtype=int64),)
[[2 3]]
